### ISSUE TITLE
Error on first Phantom after implementing. 

### ISSUE THREAD

**Issue by emc2sj** [chuushi/PhantomSMP#2]
Hi, 

I downloaded your plugin and it's throwing errors. Any ideas? Thanks in advance.

1:22:07 PM [ERROR] Could not pass event CreatureSpawnEvent to PhantomSMP v1.0.2
1:22:07 PM org.bukkit.event.EventException: null
1:22:07 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:287) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.World.addEntity(World.java:911) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.WorldServer.addEntity(WorldServer.java:942) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.MobSpawnerPhantom.a(MobSpawnerPhantom.java:57) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.ChunkProviderGenerate.a(ChunkProviderGenerate.java:256) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at org.bukkit.craftbukkit.v1_13_R1.generator.NormalChunkGenerator.a(NormalChunkGenerator.java:74) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.ChunkProviderServer.a(ChunkProviderServer.java:376) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.WorldServer.doTick(WorldServer.java:279) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:940) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
1:22:07 PM Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Phantom.getTarget()Lorg/bukkit/entity/LivingEntity;
1:22:07 PM at com.simonorj.mc.phantomsmp.PhantomSMP.addPhantom(PhantomSMP.java:72) ~[?:?]
1:22:07 PM at com.simonorj.mc.phantomsmp.PhantomSMP.addPhantom(PhantomSMP.java:68) ~[?:?]
1:22:07 PM at com.simonorj.mc.phantomsmp.PhantomSMP.access$300(PhantomSMP.java:27) ~[?:?]
1:22:07 PM at com.simonorj.mc.phantomsmp.PhantomSMP$PhantomListener.phantomSpawn(PhantomSMP.java:150) ~[?:?]
1:22:07 PM at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source) ~[?:?]
1:22:07 PM at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
1:22:07 PM at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
1:22:07 PM at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
1:22:07 PM ... 16 more
1:22:07 PM [ERROR] Could not pass event CreatureSpawnEvent to PhantomSMP v1.0.2

**Comment by chuushi** [comment]
Thank you for the report; I'll look into it

**Comment by chuushi** [comment]
Your Spigot is outdated. Tell me if the issue persists after you update Spigot to the latest build.

The plugin uses the interface added to Bukkit on August 10, and your build seems to be built on August 6.
