### ISSUE TITLE
Merge Minebench's improvements

### ISSUE THREAD

**Issue by MilesBHuff** [chuushi/PhantomSMP#9]
While this plugin has been dead for some time, there appears to be a somewhat active fork;  however, this fork has no releases, and has not performed any rebranding;  meaning they have no interest in going through the trouble of publishing it as a separate plugin.  That's a shame, because a number of people use this plugin, and those improvements would doubtless help everyone.  I was hoping you could consider merging said improvements.  Here's a link to the fork:  https://github.com/Minebench/PhantomSMP.  I tried to create a PR from that repo to this one;  but I was not allowed to for some reason (The error message was cryptic.).

**Comment by chuushi** [comment]
As much as I like PaperMC, I would like to also keep support for Spigot servers. PaperMC mostly eliminates the need for this plugin by taking care of the Phantom mechanics with these two flags:

* `phantoms-only-attack-insomniacs` replacing this plugin's `remove-targeting-rested` option
* `phantoms-do-not-spawn-on-creative-players`, a rather toggle that I did not cover in this plugin.

However, I do understand that some people would like more fine-grained control over phantom mechanics. I will see and get the requested commit through while keeping Spigot supported at the minimum.

Thanks!

**Comment by Phoenix616** [comment]
Btw. if anyone really needs my fork with the added paper improvements and can't build it themselves, our build server has [builds](https://ci.minebench.de/job/PhantomSMP/) of it.

Also thanks for pointing out the paper options, gonna have to look into whether or not I personally even need the plugin anymore 👀

**Comment by chuushi** [comment]
I've jumped from 1.16.5 and started 1.18.1 world without this plugin, haha. Thanks for allowing us to use your code, Phoenix!

**Comment by chuushi** [comment]
https://github.com/chuushi/PhantomSMP/tree/v1.1.2
